import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

const nextStaticDir =
    path.join(root, ".next", "static");

const publicDir =
    path.join(root, "public");

const outputFile =
    path.join(publicDir, "sw.js");

function walk(directory) {
    if (!fs.existsSync(directory)) {
        return [];
    }

    const result = [];

    for (const entry of fs.readdirSync(
        directory,
        { withFileTypes: true }
    )) {
        const fullPath =
            path.join(
                directory,
                entry.name
            );

        if (entry.isDirectory()) {
            result.push(
                ...walk(fullPath)
            );
        } else {
            result.push(fullPath);
        }
    }

    return result;
}

function toPublicUrl(file) {
    const relative =
        path.relative(
            publicDir,
            file
        );

    return (
        "/" +
        relative
            .split(path.sep)
            .map(encodeURIComponent)
            .join("/")
    );
}

function toNextStaticUrl(file) {
    const relative =
        path.relative(
            nextStaticDir,
            file
        );

    return (
        "/_next/static/" +
        relative
            .split(path.sep)
            .map(encodeURIComponent)
            .join("/")
    );
}

/*
 * Everything generated by Next that belongs
 * to the static application runtime.
 */
const nextAssets =
    walk(nextStaticDir)
        .map(toNextStaticUrl);

/*
 * Everything in public becomes part of
 * the offline application shell.
 *
 * The SW itself is excluded because it is
 * the update mechanism.
 */
const publicAssets =
    walk(publicDir)
        .filter(
            (file) =>
                path.basename(file) !==
                    "sw.js" &&
                path.basename(file) !==
                    "app-shell.json"
        )
        .map(toPublicUrl);

/*
 * The root document is the application shell.
 */
const precache =
    Array.from(
        new Set([
            "/",
            ...nextAssets,
            ...publicAssets,
        ])
    ).sort();

const existingSw =
    fs.existsSync(outputFile)
        ? fs.readFileSync(
              outputFile,
              "utf8"
          )
        : "";

const versionMatch =
    existingSw.match(
        /const APP_VERSION = "([^"]+)";/
    );

const currentVersion =
    versionMatch
        ? versionMatch[1]
        : "0";

const parts =
    currentVersion
        .split(".")
        .map(Number);

parts[parts.length - 1]++;

const nextVersion =
    parts.join(".");

const sw = `const APP_VERSION = "${nextVersion}";
const CACHE_NAME = \`ccc-app-\${APP_VERSION}\`;

const PRECACHE = ${JSON.stringify(
    precache,
    null,
    4
)};

/* -------------------------------------------------------------------------- */
/* Install                                                                    */
/* -------------------------------------------------------------------------- */

self.addEventListener("install", (event) => {
    event.waitUntil(
        caches
            .open(CACHE_NAME)
            .then((cache) =>
                cache.addAll(PRECACHE)
            )
    );

    self.skipWaiting();
});

/* -------------------------------------------------------------------------- */
/* Activate                                                                   */
/* -------------------------------------------------------------------------- */

self.addEventListener("activate", (event) => {
    event.waitUntil(
        (async () => {
            const keys =
                await caches.keys();

            await Promise.all(
                keys
                    .filter(
                        (key) =>
                            key.startsWith(
                                "ccc-app-"
                            ) &&
                            key !==
                                CACHE_NAME
                    )
                    .map((key) =>
                        caches.delete(key)
                    )
            );

            await self.clients.claim();

            const clients =
                await self.clients.matchAll({
                    type: "window",
                    includeUncontrolled: true,
                });

            for (const client of clients) {
                client.postMessage({
                    type: "APP_VERSION",
                    version: APP_VERSION,
                });
            }
        })()
    );
});

/* -------------------------------------------------------------------------- */
/* Fetch                                                                      */
/* -------------------------------------------------------------------------- */

self.addEventListener("fetch", (event) => {
    const request =
        event.request;

    if (
        request.method !== "GET"
    ) {
        return;
    }

    const url =
        new URL(request.url);

    if (
        url.origin !== self.location.origin
    ) {
        return;
    }

    /*
     * APIs/authentication are deliberately
     * excluded from the offline application.
     */
    if (
        url.pathname.startsWith("/api/")
    ) {
        return;
    }

    event.respondWith(
        offlineFirst(request)
    );
});

/* -------------------------------------------------------------------------- */
/* Offline First                                                              */
/* -------------------------------------------------------------------------- */

async function offlineFirst(request) {
    const cached =
        await caches.match(request);

    if (cached) {
        return cached;
    }

    try {
        const response =
            await fetch(request);

        if (
            response.ok &&
            response.type === "basic"
        ) {
            const cache =
                await caches.open(
                    CACHE_NAME
                );

            await cache.put(
                request,
                response.clone()
            );
        }

        return response;
    } catch {
        /*
         * For an unvisited navigation,
         * fall back to the application shell.
         */
        if (
            request.mode === "navigate"
        ) {
            const shell =
                await caches.match("/");

            if (shell) {
                return shell;
            }
        }

        throw new Error(
            "Resource unavailable offline."
        );
    }
}
`;

fs.writeFileSync(
    outputFile,
    sw
);

console.log(
    `Generated service worker ${nextVersion}`
);

console.log(
    `Precached ${precache.length} assets`
);